### ISSUE TITLE
点击Submit，页面显示错误，控制台显示AttributeError: 'PrelrainedlokenizerFast' object has no attribute  'build_chat_input'

### ISSUE THREAD

**Issue by 1105135335** [THUDM/LongWriter#10]
### System Info / 系統信息

CUDA ：11.1
transformers：4.44.0
Python：3.10.0
操作系统：Windows10 64

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 在conda控制台进入项目路径并进入搭好环境的虚拟环境，然后运行python trans_web_demo.py；
2. 项目正常运行启动并自动弹出网页；
3. 在输入框中输入”User: 写一篇10000字的中国旅游指南“，点击Submit。出现如下午所示的错误。

![1](https://github.com/user-attachments/assets/c7b9974d-6e99-4ada-b1ad-f8c127451a12)

![2](https://github.com/user-attachments/assets/c3d0868a-2669-48b5-8631-9dfd052147f6)

### Expected behavior / 期待表现

在输入框中输入示例中的”User: 写一篇10000字的中国旅游指南“，点击Submit，正常生成例如示例中的1w+内容。

**Comment by bys0318** [comment]
hi, please update to the newest [trans_web_demo.py](https://github.com/THUDM/LongWriter/blob/main/trans_web_demo.py).

**Comment by yungongzi** [comment]
- 使用LongWriter-llama3.1-8b
- 模型更新到最新代码，transformers==4.44.0，
- 依然报错：
`Traceback (most recent call last):
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/blocks.py", line 1525, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/utils.py", line 656, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/utils.py", line 649, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/hadoop/miniconda3/envs/zhipuai/lib/python3.11/site-packages/gradio/utils.py", line 815, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/JjtGPT/stang_llm/LongWriter/trans_web_demo.py", line 81, in predict
    model_inputs = tokenizer.build_chat_input(query, history=messages, role='user').input_ids.to(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PreTrainedTokenizerFast' object has no attribute 'build_chat_input'
`

**Comment by bys0318** [comment]
你好，我们提供的trans_web_demo.py示例代码适配的是LongWriter-glm4-9b模型，如果要在LongWriter-llama3.1-8b上尝试此demo需要更改代码，请参考[hf readme](https://huggingface.co/THUDM/LongWriter-llama3.1-8b)中的推理代码进行更改。

**Comment by yungongzi** [comment]
> 你好，我们提供的trans_web_demo.py示例代码适配的是LongWriter-glm4-9b模型，如果要在LongWriter-llama3.1-8b上尝试此demo需要更改代码，请参考[hf readme](https://huggingface.co/THUDM/LongWriter-llama3.1-8b)中的推理代码进行更改。
多谢，我去试一下
