### ISSUE TITLE
cache_name, cache = self._extract_past_from_model_output(outputs) ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by seetimee** [THUDM/LongWriter#6]
Traceback (most recent call last):
  File "/data/stephen/miniconda3/envs/longtext/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/stephen/miniconda3/envs/longtext/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/stephen/miniconda3/envs/longtext/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/stephen/miniconda3/envs/longtext/lib/python3.10/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/data/stephen/miniconda3/envs/longtext/lib/python3.10/site-packages/transformers/generation/utils.py", line 2778, in sample
    model_kwargs = self._update_model_kwargs_for_generation(
  File "/data/stephen/.cache/huggingface/modules/transformers_modules/THUDM/LongWriter-glm4-9b/81b025e373d163efd7908a787b3fb907424c6184/modeling_chatglm.py", line 739, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(outputs)
ValueError: too many values to unpack (expected 2)

**Comment by seetimee** [comment]
after pip install transformers --upgrade it fixed . Please update the requirments.txt

**Comment by bys0318** [comment]
Thanks for bringing this issue to our notice. The `requirement.txt` is for model training, I will add an explanation on this.
